steps:
# Construye la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-express-app:$COMMIT_SHA', '.']

# Sube la imagen a Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-express-app:$COMMIT_SHA']

# Despliega la imagen en Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - my-express-app
  - --image=gcr.io/$PROJECT_ID/my-express-app:$COMMIT_SHA
  - --platform=managed
  - --region=northamerica-south1  # Asegúrate de usar la región de tu preferencia
  - --allow-unauthenticated # Omitir si quieres que sea privado

images:
- gcr.io/$PROJECT_ID/my-express-app:$COMMIT_SHA